platform :ios, '9.3'
use_frameworks!

target 'CentrifugeiOS_Example' do
    pod 'CentrifugeiOS', :path => '../'
end

target 'CentrifugeiOS_Tests' do
    pod 'CentrifugeiOS', :path => '../'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            if target.name == 'SwiftWebSocket'
                target.build_settings(configuration.name)['SWIFT_VERSION'] = '3.0'
            end
        end
    end
end
